import { query } from "./_generated/server";
import { v } from "convex/values";
import { requireUser } from "./authHelper";

export interface VaultFile {
  path: string;
  filename: string;
  content: string;
}

/**
 * Generates an Obsidian-compatible markdown vault projection using [[wikilinks]].
 * Conforms to Section 30 & Section 48 of the Maana Codex Build Guide.
 */
export const generateGoalVault = query({
  args: {
    goalId: v.id("goals"),
  },
  handler: async (ctx, args) => {
    const { userId } = await requireUser(ctx);

    const goal = await ctx.db.get(args.goalId);
    if (!goal || goal.userId !== userId) {
      throw new Error("Goal not found or unauthorized");
    }

    const allNodes = await ctx.db
      .query("nodes")
      .withIndex("by_goal", (q) => q.eq("goalId", args.goalId))
      .collect();

    const allActivities = await ctx.db
      .query("activities")
      .withIndex("by_goal_started", (q) => q.eq("goalId", args.goalId))
      .collect();

    const allDecisions = await ctx.db
      .query("decisions")
      .withIndex("by_goal_created", (q) => q.eq("goalId", args.goalId))
      .collect();

    const allResearch = await ctx.db
      .query("research")
      .withIndex("by_goal", (q) => q.eq("goalId", args.goalId))
      .collect();

    const nodeMap = new Map(allNodes.map((n) => [n._id, n]));
    const files: VaultFile[] = [];

    const sanitizeFilename = (name: string) =>
      name.replace(/[/\\?%*:|"<>]/g, "-").trim();

    // 1. Goal Overview File
    const goalFilename = sanitizeFilename(goal.title);
    const goalBranches = allNodes
      .map((n) => `- [[${sanitizeFilename(n.title)}]] (${n.type}) — *${n.status}*`)
      .join("\n");

    const goalContent = `# ${goal.title}

Status: ${goal.status}
Created: ${new Date(goal.createdAt).toISOString()}

## Intent Description
Preserving continuity for high-level objective: "${goal.title}"

## Discovered Work Graph & Branches
${goalBranches || "No branches discovered yet."}

## Autonomous Decisions Ledger
${
  allDecisions.length > 0
    ? allDecisions
        .map(
          (d) =>
            `- [[Decision - ${d.classification.toUpperCase()}]] (Confidence: ${Math.round(
              d.confidence * 100
            )}% via ${d.model}): ${d.reason}`
        )
        .join("\n")
    : "No cognitive decisions recorded yet."
}
`;
    files.push({
      path: `Goals/${goalFilename}.md`,
      filename: `${goalFilename}.md`,
      content: goalContent,
    });

    // 2. Individual Branch & Node Files
    for (const node of allNodes) {
      const nodeFilename = sanitizeFilename(node.title);
      const parentNode = node.parentId ? nodeMap.get(node.parentId) : undefined;
      const parentLink = parentNode
        ? `[[${sanitizeFilename(parentNode.title)}]]`
        : `[[${goalFilename}]]`;

      const nodeActivities = allActivities.filter((a) => a.nodeId === node._id);
      const nodeDecisions = allDecisions.filter((d) => d.nodeId === node._id);
      const nodeResearch = allResearch.filter((r) => r.nodeId === node._id);

      const activityList =
        nodeActivities.length > 0
          ? nodeActivities
              .map(
                (a) =>
                  `- [[${sanitizeFilename(a.title)}]] (${a.app}) — ${
                    a.durationMs
                      ? `${Math.round(a.durationMs / 60000)}m`
                      : "active"
                  }`
              )
              .join("\n")
          : "- *No isolated activities logged for this node.*";

      const researchList =
        nodeResearch.length > 0
          ? nodeResearch
              .map(
                (r) =>
                  `- **Query:** "${r.query}"\n  - Sources: ${r.sourceUrls
                    .map((url) => `[${url}](${url})`)
                    .join(", ")}`
              )
              .join("\n")
          : "- *No external Firecrawl research needed.*";

      const branchContent = `# ${node.title}

Parent: ${parentLink}
Type: ${node.type}
Status: ${node.status}

## Why this branch exists
${node.reason || "Autonomous inference generated by Maana cognitive reasoning engine."}

## Agent Confidence
${node.confidence !== undefined ? `${node.confidence}` : "1.0"}

## Associated Work Activities
${activityList}

## Inferred Decisions
${
  nodeDecisions.length > 0
    ? nodeDecisions
        .map(
          (d) =>
            `- Classification: **${d.classification.toUpperCase()}** (${Math.round(
              d.confidence * 100
            )}%)\n  *${d.reason}*`
        )
        .join("\n")
    : "- *Directly attached or user-initiated branch.*"
}

## External Firecrawl Research
${researchList}
`;

      files.push({
        path: `Branches/${nodeFilename}.md`,
        filename: `${nodeFilename}.md`,
        content: branchContent,
      });
    }

    // 3. Daily Review File
    const todayDate = new Date().toISOString().split("T")[0];
    const dailyFilename = `${todayDate}.md`;

    const activeNode = goal.currentNodeId
      ? nodeMap.get(goal.currentNodeId)
      : undefined;

    const dailyContent = `# ${todayDate} — Daily Work Session Review

## Active Intent
[[${goalFilename}]]

## Current Focused Path
${
  activeNode
    ? `→ [[${sanitizeFilename(activeNode.title)}]] (${activeNode.type})`
    : "No active focus node selected."
}

## Discovered Branches Today
${
  allNodes.length > 0
    ? allNodes.map((n) => `- [[${sanitizeFilename(n.title)}]]`).join("\n")
    : "None"
}

## Decisions Trace Summary
${
  allDecisions.length > 0
    ? allDecisions
        .slice(0, 5)
        .map(
          (d) =>
            `- **${d.classification.toUpperCase()}**: ${d.reason} (${Math.round(
              d.confidence * 100
            )}% confidence)`
        )
        .join("\n")
    : "No decisions recorded today."
}

## Daily Review Invariants
- Graph Hypothesis Reconciled: ✓
- User Continuity Preserved: ✓
- Zero Clerical Maintenance Required: ✓
`;

    files.push({
      path: `Daily/${dailyFilename}`,
      filename: dailyFilename,
      content: dailyContent,
    });

    return {
      goalTitle: goal.title,
      fileCount: files.length,
      files,
    };
  },
});
